CREATE DATABASE IF NOT EXISTS ${db_name};
CREATE DATABASE IF NOT EXISTS ${raw_db_name};
CREATE DATABASE IF NOT EXISTS ${replicated_db_name};
CREATE DATABASE IF NOT EXISTS ${unified_db_name};
CREATE DATABASE IF NOT EXISTS airflow;
CREATE DATABASE IF NOT EXISTS hop;