name: Scheduled Terraform Destroy

on:
  schedule:
    - cron: '0 15 * * *'   # 8:30 PM IST daily

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-destroy-dev
  cancel-in-progress: false

jobs:

  terraform-destroy:

    runs-on: ubuntu-latest

    timeout-minutes: 90

    environment: dev

    defaults:
      run:
        working-directory: infra

    env:
      TF_IN_AUTOMATION: true
      ENVIRONMENT: dev

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::986401823783:role/bpay-etl-githubaction-role
          aws-region: ap-south-1
          
      - name: Verify AWS Login
        run: |
          aws sts get-caller-identity

      - name: Create EC2 PEM file
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > bastion-key.pem
          chmod 400 bastion-key.pem

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: |
          terraform init -upgrade \
            -backend-config="key=bpay-etl/${ENVIRONMENT}/terraform.tfstate"

      - name: Terraform Validate
        run: terraform validate

      - name: Delete Hop ECR Image
        run: |
          aws ecr batch-delete-image \
            --repository-name glorytechsystems-platform-images \
            --image-ids imageTag=bpay-etl-${ENVIRONMENT} \
            --region ap-south-1 || true

      - name: Terraform Destroy
        run: |
          terraform destroy \
            -parallelism=20 \
            -auto-approve \
            -var-file=environments/${ENVIRONMENT}.tfvars